name: SC3Tech
favicon: null
layout_spectrum: 0.9334558409173042
typography_spectrum: 0.75898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b69f91'
    - '#333333'
    - '#847270'
    - '#555651'
    - '#a6c7b4'
  brandStrength: 0.5
  lightness: 0.209169112611562
  saturation: 0.1560461858753115
  rhythmicContrast: 0.3110369991045445
purpose: []
