name: SC3Tech
favicon: null
layout_spectrum: 0.9334558409173042
typography_spectrum: 0.9252982952166349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.13867962756194174
  lightness: 0.209169112611562
  saturation: 0.1560461858753115
  rhythmicContrast: 0.3110369991045445
purpose: []
